In [1]:
import os
import sys
from core.data_loader import DataLoader
from db.ods import connectionOds
from core.risk_compute import RiskComputer

In [2]:

# Initialisation des connexions aux bases de données
oracle_engine = connectionOds()
connect = oracle_engine.connect()

#print(f"Postgres DB Host: {POSTGRES_DB_HOST} Port: {POSTGRES_DB_PORT} User: {POSTGRES_DB_USER} DB: {POSTGRES_DB_NAME}")

engine  SIDDGI database successful

In [3]:
loader = DataLoader(oracle_engine)
computer = RiskComputer()

2026-02-16 16:00:21,335 - core.data_loader - INFO - Chargement des données de référence...
2026-02-16 16:00:21,800 - core.data_loader - INFO - NON_EIGIBLE.xlsx chargé: 6204 IFU exclus
2026-02-16 16:00:21,800 - core.data_loader - INFO - Entreprises_LIEES.xlsx chargé: 100 lignes
2026-02-16 16:00:21,818 - core.data_loader - INFO - ../docs/META_DONNEES.xlsx chargé
2026-02-16 16:00:21,842 - core.data_loader - INFO - ../docs/FICHE_PISTES_INVESTIGATION.xlsx chargé
2026-02-16 16:00:22,132 - core.data_loader - INFO - ../docs/NomenclatureSH.xlsx chargé
2026-02-16 16:00:22,153 - core.data_loader - INFO - ../docs/DCF_ACTIVITES.xlsx chargé
2026-02-16 16:00:22,153 - core.risk_compute - INFO - Chargement des données de référence...
2026-02-16 16:00:22,365 - core.risk_compute - INFO - NON_EIGIBLE.xlsx chargé: 6984 IFU a exclur
2026-02-16 16:00:22,382 - core.risk_compute - INFO - Entreprises_LIEES.xlsx chargé: 100 lignes

In [4]:
data_dict = loader.extract_complete_oracle_data()

2026-02-13 16:23:09,426 - core.data_loader - INFO -  1.=== EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2026-02-13 16:23:09,514 - core.data_loader - INFO - Extraction contribuables
2026-02-13 16:24:52,151 - core.data_loader - INFO - Contribuables extraits: 695065/695065 après exclusions en 102.64s
2026-02-13 16:24:52,151 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2026-02-13 16:25:01,568 - core.data_loader - INFO - BD_TVA construite (R-compatible): 59034 lignes en 9.42s
2026-02-13 16:25:01,568 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2026-02-13 16:25:17,695 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 62082 lignes en 16.13s
2026-02-13 16:25:17,695 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2026-02-13 16:25:25,543 - core.data_loader - INFO - DGD extraite de la base Oracle: 37349 lignes
2026-02-13 16:25:25,543 - core.data_loader - INFO - DGD complète extraite: 37349 lignes en 7.85s
2026-02-13 16:25:25,543 - core.data_loader - INFO - Extraction programmation et contrôles
2026-02-13 16:25:27,160 - core.data_loader - INFO - Programmation extraite: 12654 lignes en 1.62s
2026-02-13 16:25:27,160 - core.data_loader - INFO - Extraction bénéfices complets
2026-02-13 16:25:51,052 - core.data_loader - INFO - Bénéfices extraits: 35478 lignes en 23.89s
2026-02-13 16:25:51,052 - core.data_loader - INFO - Extraction INSD
2026-02-13 16:25:53,526 - core.data_loader - INFO - INSD extraite: 7487 lignes en 2.47s

In [4]:
data_from_process = loader.run_extract_merge()

2026-02-16 16:00:33,646 - core.data_loader - INFO - === EXTRACTION & FUSION ===
2026-02-16 16:00:33,652 - core.data_loader - INFO -  1.=== EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2026-02-16 16:00:33,851 - core.data_loader - INFO - Extraction contribuables
2026-02-16 16:02:37,318 - core.data_loader - INFO - Contribuables extraits: 695618/695618 après exclusions en 123.47s
2026-02-16 16:02:37,318 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2026-02-16 16:02:48,006 - core.data_loader - INFO - BD_TVA construite (R-compatible): 59034 lignes en 10.69s
2026-02-16 16:02:48,006 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2026-02-16 16:03:06,261 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 62082 lignes en 18.25s
2026-02-16 16:03:06,264 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2026-02-16 16:03:13,963 - core.data_loader - INFO - DGD extraite de la base Oracle: 37422 lignes
2026-02-16 16:03:13,966 - core.data_loader - INFO - DGD complète extraite: 37422 lignes en 7.70s
2026-02-16 16:03:13,966 - core.data_loader - INFO - Extraction programmation et contrôles
2026-02-16 16:03:15,529 - core.data_loader - INFO - Programmation extraite: 12654 lignes en 1.56s
2026-02-16 16:03:15,529 - core.data_loader - INFO - Extraction bénéfices complets
2026-02-16 16:03:39,791 - core.data_loader - INFO - Bénéfices extraits: 35478 lignes en 24.26s
2026-02-16 16:03:39,791 - core.data_loader - INFO - Extraction INSD
2026-02-16 16:03:42,100 - core.data_loader - INFO - INSD extraite: 7487 lignes en 2.31s
2026-02-16 16:03:42,121 - core.data_loader - INFO - Étape d'extraction terminée en 188.47s
2026-02-16 16:03:42,121 - core.data_loader - INFO - 2.=== FUSION DES DONNÉES ===
2026-02-16 16:03:43,278 - core.data_loader - INFO - Fusion avec BD_TVA: 741616 lignes
2026-02-16 16:03:45,900 - core.data_loader - INFO - Fusion avec DCF_TVA_DEDUCTION: 768733 lignes
2026-02-16 16:03:48,556 - core.data_loader - INFO - Fusion avec DGD: 789506 lignes
2026-02-16 16:03:50,281 - core.data_loader - INFO - Fusion avec Programmation|controlle: 789506 lignes
2026-02-16 16:03:52,707 - core.data_loader - INFO - Fusion avec Bénéfices: 809964 lignes
2026-02-16 16:03:56,016 - core.data_loader - INFO - Fusion avec INSD: 810647 lignes
2026-02-16 16:04:42,915 - core.data_loader - INFO - Étape de fusion terminée en 60.79s

In [13]:
date_derniere_vg = "2025-12-31"
date_derniere_vp = "2025-12-31"
date_derniere_avis = "2025-12-31"

In [28]:
data_from_process["DATE_DERNIERE_VP"].value_counts()

Series([], Name: count, dtype: int64)

In [14]:
merged_data = data_from_process[(data_from_process["DATE_DERNIERE_VG"]<date_derniere_vg)& 
            (data_from_process["DATE_DERNIERE_AVIS"]<date_derniere_avis) &
            (data_from_process["DATE_DERNIERE_VP"]<date_derniere_vp)]

In [15]:
merged_data

Empty DataFrame
Columns: [ID_CONTR, NUM_IFU, NOM_x, NOM_MINEFID, DATE_CREATION, DATE_IMMAT, ETAT, TEL, EMAIL, CODE_FJ, CODE_REG_FISC, CODE_SECT_ACT, CAPITAL, CHIF_AFFAIREPREV, ADR_CTR, NATIONALITE_CTR, FLAG_RESIDENT, NOCNSS, FLAG_EMPLOYEUR, STRUCTURES, LIBELLE_SECT_ACT, LIBELLE_GR_SECT_ACT, NOM_y, ANNEE_FISCAL_x, MONTANT_DECLARE, OP_TAXBLE_COURANTE_VENTES_PRESTATIONS_SERVICES_TRVX_IMMO_01, OP_TAXBLE_COURANTE_LIVRAISON_A_SOI_MEME_02, OP_TAXBLE_COURANTE_CESSION_IMMO_03, OP_TAXBLE_COURANTE_OPERATION_TAXABLE_TAUX_10PC_218, OP_TAXBLE_COURANTE_AUTRES_OPERATIONS_TAXABLES_04, OP_TAXBLE_MARCHE_CDE_VENTES_05, OP_TAXBLE_MARCHE_CDE_PRESTATION_SERVICES_06, OP_TAXBLE_MARCHE_CDE_TRAVAUX_IMMO_TRVX_PUPLIC_07, OP_TAXBLE_MARCHE_CDE_10PC_220, OP_TAXBLE_MARCHE_CDE_AUTRES_OP_TAXABLES_08, OP_NTAXBLE_EXPORTATIONS_09, OP_NTAXBLE_AUTRES_COMM_EXTERIEUR_VTE_SUSPENSION_TAXE_10, OP_NTAXBLE_AUTRES_OP_NON_TAXABLE_11, TVA_AU_TAUX_185PC_12, SOUMISE_AU_TAUX_REDUIT_10PC_219, TVA_BRUTE_OMISE_REVERSER_13, TVA_ANT_DEDUITE_A_REVERSER_14, MONTANT_TOTAL_LA_BRUTE_15, TVA_DEDUCTIBLE_PÉRIODE_16, CREDIT_TVA_PERIODE_PRECEDENTE_17, CREDIT_TVA_DDE_REMBOURSEMENT_18, CREDIT_TVA_REMBOURSEMENT_NON_DEMANDE_19, TVA_VENTE_SERVICES_IMPAYES_CREANCE_IRECOUVRABLE_20, TVA_VTE_SERVICE_RESILIES_21, AUTRES_DEDUCTIONS_22, CREDIT_TVA_NON_REMBOURSE_23, MONTANT_TVA_PAYABLE_AVIS_CREDIT_127, MONTANT_TVA_NET_A_PAYER_25, MONTANT_TOTAL_OPERATIONS_24, CREDIT_TVA_A_REMBOURSER_26, NB_DECLARATIONS, TVA_DECEMBRE, ANNEE, CLI_TVA_DEDUCTIBLE_NOV_DEC, CLI_PR_HT_NOV_DEC, CLI_TVA_FACTURE_NOV_DEC, FOURN_TVA_DEDUCTIBLE_NOV_DEC, FOURN_PR_HT_NOV_DEC, FOURN_TVA_FACTURE_NOV_DEC, CLI_TVA_DEDUCTIBLE_AN, CLI_PR_HT_AN, CLI_TVA_FACTURE_AN, FOURN_TVA_DEDUCTIBLE_AN, FOURN_PR_HT_AN, FOURN_TVA_FACTURE_AN, TVA_SUPPORTE_IMPORT, IMPORT_CAF, IMPORT_FOB, IMPORT_TVA, EXPORT_CAF, EXPORT_FOB, EXPORT_TVA, IMPORT_NOMBRE_TITRE, EXPORT_NOMBRE_TITRE, DATE_DERNIERE_VG, DATE_DERNIERE_VP, DATE_DERNIERE_AVIS, DERNIERE_GESTION_SOUMIS_VERIF, ANNEE_FISCAL_y, CA_HTVA, BENEFICE_IMPOSABLE, IBENEF_EXIGIBLE, IBENEF_DUES, PREL_SOURCE_ACOMPTE, RETENUE_SOURCE_IMPUTE, FRAISDEVPROSP_ACQAPCREAT, FRAISDEVPROSP_VIREPOSTPOST, BREVLICLOGDROISIM_ACQAPCREAT, BREVLICLOGDROISIM_VIREPOSTPOST, FDSCOMMDROIB_ACQAPCREAT, FDSCOMMDROIB_VIREPOSTPOST, AUTRIMMBINCORP_ACQAPCREAT, AUTRIMMBINCORP_VIREPOSTPOST, TERRHORSIMMEPLAC_ACQAPCREAT, TERRHORSIMMEPLAC_VIREPOSTPOST, ...]
Index: []

[0 rows x 141 columns]

In [5]:
r = computer.run(data=data_from_process)

2026-02-16 16:04:58,681 - core.risk_compute - INFO - === DÉMARRAGE PROCESSUS: RECUPERATION & CALCUL DES RISQUES ===
2026-02-16 16:04:59,977 - core.risk_compute - INFO - Données chargées et mergées avec succès: 810647 lignes
2026-02-16 16:04:59,987 - core.risk_compute - INFO - === CALCUL DE 32 INDICATEURS ===
2026-02-16 16:04:59,987 - core.risk_compute - INFO - 1.avant filtre: 810647 lignes
2026-02-16 16:05:00,027 - core.risk_compute - INFO - 2.apres filtre: 0 lignes
2026-02-16 16:05:00,027 - core.risk_compute - INFO - Colonnes de base initialisées: 10 colonnes
2026-02-16 16:05:00,182 - core.risk_compute - INFO - Calcul de tous les indicateurs terminé
2026-02-16 16:05:00,185 - core.risk_compute - ERROR - Erreur de validation: Le calcul des indicateurs n'a produit aucun résultat
2026-02-16 16:05:00,185 - core.risk_compute - ERROR - Traceback (most recent call last):
  File "d:\DGI\project\ANARISK_APP\anarisk_backend\src\core\risk_compute.py", line 374, in run
    raise ValueError("Le calcul des indicateurs n'a produit aucun résultat")
ValueError: Le calcul des indicateurs n'a produit aucun résultat

In [ ]:
loader.dcf_activites.to_sql(
     name='dcf_activites',
    con=connect,
    schema='PROG_DCF',
    if_exists='append',  # Ajouter sans écraser
    index=False)

In [19]:
full_data["contribuables"]

,ID_CONTR,NUM_IFU,NOM,NOM_MINEFID,DATE_CREATION,DATE_IMMAT,ETAT,TEL,EMAIL,CODE_FJ,CODE_REG_FISC,CODE_SECT_ACT,CAPITAL,CHIF_AFFAIREPREV,ADR_CTR,NATIONALITE_CTR,FLAG_RESIDENT,NOCNSS,FLAG_EMPLOYEUR,STRUCTURES
0,455301,00000003T,MAROU LENGLENGUE,MAROU LENGLENGUE,2006-01-12 00:00:00,2006-01-13 00:00:00,ACTIF,70-11-29-77,None,43,CME,7433,NaN,NaN,01 BP 3924 OUAGA 01,35,NON,None,NON,DCI-OUAGA 5
2,455656,00000005J,MAHAMADI ZOUNGRANA,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),2006-02-03 00:00:00,2006-02-03 00:00:00,ACTIF,50303511,None,43,CME,5226,NaN,NaN,10 BP 13445 OUAGADOUGOU 10,35,NON,33277W,NON,DCI-OUAGA 1
3,455304,00000007Y,CLEMENT BASSONO,CLEMENT BASSONO (GENIE MULTI-SERVICES),2006-01-12 00:00:00,2006-01-13 00:00:00,ACTIF,70-23-96-06,None,43,CME,5227,0.0,0.0,06 BP 9145 OUAGA 06,35,NON,None,NON,DCI-OUAGA 5
4,455310,00000018K,LAMOUSSA HAMED GANEMTORE,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,2006-01-16 00:00:00,2006-01-16 00:00:00,ACTIF,50-37-19-15,None,43,CME,5030,NaN,NaN,01 BP 3274 OUAGA 01,35,NON,None,NON,DCI-OUAGA 8
5,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16 00:00:00,2006-01-16 00:00:00,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,RN,5222,NaN,NaN,01 BP 1984 OUAGA 01,35,NON,None,NON,DME/CENTRE II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213977,1178813,00281794C,SOUMAILA SILGA,SOUMAILA SILGA (S.SILGA),2025-08-26 11:52:55,2025-08-26 13:52:55,ACTIF,+226-70-40-17-60,None,43,ND,0170,0.0,0.0,KOUPELA,35,OUI,None,NON,KOURITENGA
213978,1178814,00281795Z,PHAROUCK OUMAROU ILBOUDO,PHAROUCK OUMAROU ILBOUDO (PHAROUCK ENERBAT),2025-08-26 11:53:47,2025-08-26 13:53:47,ACTIF,76-43-96-75,ILBOUDOPHAROUCKOUMAROU@GMAIL.C,43,CME,4530,0.0,1000000.0,S/C 01 BV 30642 OUAGA CNTC,35,OUI,None,NON,DCI-OUAGA 7
213979,1178767,00281797E,AZIZ SEDEGO,AZIZ SEDEGO (ENTREPRISE SEDEGO AZIZ),2025-08-26 11:56:42,2025-08-26 13:56:42,ACTIF,56-64-51-59,SEDEGOAZIZ94@GMAIL.COM,43,CME,1592,0.0,1000000.0,S/C 01 BV 30642 OUAGA CNTC,35,OUI,None,NON,DCI-OUAGA 5
213980,1178820,00281798H,ABDOULAYE SEBGO,ABDOULAYE SEBGO (AKOS TRANSFERT),2025-08-26 11:58:27,2025-08-26 13:58:27,ACTIF,77-61-30-30,ABDOULAYESEBGO22@GMAIL.COM,43,CME,5210,0.0,1000000.0,S/C 01 BP 5808 OUAGA 01,35,OUI,None,NON,DCI-OUAGA 3
213981,1178796,00281799T,RAGNANGNEWENDE BERTIN ILBOUDO,RAGNANGNEWENDE BERTIN ILBOUDO,2025-08-26 11:59:06,2025-08-26 13:59:06,ACTIF,00226-76-23-00-80,None,43,ND,9304,0.0,0.0,SAPONE,35,OUI,None,NON,BAZEGA

In [6]:
tva = loader._construct_bd_tva_complete(oracle_engine)

2025-10-16 09:03:40,972 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-10-16 09:03:46,872 - core.data_loader - INFO - BD_TVA construite (R-compatible): 20659 lignes en 5.89s

In [7]:
tva

,NUM_IFU,NOM,ANNEE_FISCAL,MONTANT_DECLARE,OP_TAXBLE_COURANTE_VENTES_PRESTATIONS_SERVICES_TRVX_IMMO_01,OP_TAXBLE_COURANTE_LIVRAISON_A_SOI_MEME_02,OP_TAXBLE_COURANTE_CESSION_IMMO_03,OP_TAXBLE_COURANTE_OPERATION_TAXABLE_TAUX_10PC_218,OP_TAXBLE_COURANTE_AUTRES_OPERATIONS_TAXABLES_04,OP_TAXBLE_MARCHE_CDE_VENTES_05,...,TVA_VENTE_SERVICES_IMPAYES_CREANCE_IRECOUVRABLE_20,TVA_VTE_SERVICE_RESILIES_21,AUTRES_DEDUCTIONS_22,CREDIT_TVA_NON_REMBOURSE_23,MONTANT_TVA_PAYABLE_AVIS_CREDIT_127,MONTANT_TVA_NET_A_PAYER_25,MONTANT_TOTAL_OPERATIONS_24,CREDIT_TVA_A_REMBOURSER_26,NB_DECLARATIONS,TVA_DECEMBRE
0,00000004U,SCIENCES CONSULTING & TRADE,2021,25419873,0,0,0,0,0,0,...,0,0,0,0,0,25419873,141221515,0,12,1433301
1,00000004U,SCIENCES CONSULTING & TRADE,2022,14163001,0,0,0,0,0,0,...,0,0,0,0,0,14163001,78683332,0,13,0
2,00000004U,SCIENCES CONSULTING & TRADE,2023,7079944,0,0,0,0,0,0,...,0,0,0,0,0,7079944,39333020,0,9,0
3,00000017X,LAURENT AZIZ TAPSOBA,2021,24447150,0,0,0,0,0,0,...,0,0,0,0,0,24447150,135817500,0,12,0
4,00000017X,LAURENT AZIZ TAPSOBA,2022,14788800,0,0,0,0,0,0,...,0,0,0,0,0,14788800,82160000,968922,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20654,00211828C,MAISON DE LA FEMME DE DEDOUGOU,2023,36000,0,0,0,0,0,0,...,0,0,0,0,0,36000,0,0,1,0
20655,00212172B,KGL TRANSPORT & HYDROCARBURE,2023,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
20656,00213088R,DE-KU-MWIN CLARISSE SOME,2023,169821,0,0,0,0,7519203,0,...,0,0,0,0,0,169821,497658833,179182,3,0
20657,00214258M,COMPAGNIE BURKINABE SAINT CHARLES,2023,383624,0,0,0,0,0,0,...,0,0,0,0,0,383624,0,0,1,383624
20658,00217633Y,PHARMACIE NADON NOUVELLE,2023,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,5601,1,0

In [29]:
tva["NUM_IFU"].value_counts()

NUM_IFU
00172087E    3
00000178X    3
00000176W    3
00000169N    3
00000157F    3
            ..
00200837E    1
00200905A    1
00201439J    1
00201497X    1
00201566X    1
Name: count, Length: 8654, dtype: int64

In [8]:
tva_deduc = loader._extract_dcf_tva_deduction(oracle_engine)
tva_deduc

2025-10-16 09:08:30,327 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-10-16 09:08:38,592 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 100000 lignes en 8.26s

,NUM_IFU,NOM,ANNEE_FISCAL,MOIS_FISCAL,MONTANT_DECLARE,OP_TAXBLE_COURANTE_VENTES_PRESTATIONS_SERVICES_TRVX_IMMO_01,OP_TAXBLE_COURANTE_LIVRAISON_A_SOI_MEME_02,OP_TAXBLE_COURANTE_CESSION_IMMO_03,OP_NTAXBLE_EXPORTATIONS_09,OP_NTAXBLE_AUTRES_COMM_EXTERIEUR_VTE_SUSPENSION_TAXE_10,MONTANT_TVA_NET_A_PAYER_25,TVA_DEDUCTIBLE_PÉRIODE_16
0,00000004U,SCIENCES CONSULTING & TRADE,2021,1,2231195,0,0,0,0,0,2231195,0
1,00000017X,LAURENT AZIZ TAPSOBA,2021,1,0,0,0,0,0,0,0,0
2,00000019F,SYNOVIE SARL,2021,1,288882,1617034,0,0,0,0,288882,2184
3,00000051J,VERDOYANT,2021,1,4336360,31396738,0,0,0,0,4336360,1315053
4,00000063X,HAGE MATERIAUX,2021,1,71802019,761200450,0,0,9670000,0,71802019,21855823
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,00158378A,AXIAL,2023,12,6563197,0,0,0,0,0,6563197,0
99996,00158378A,AXIAL,2023,12,1464750,0,0,0,0,0,1464750,0
99997,00166442L,NOUR BATIMENT ET TRAVAUX PUBLICS,2023,12,0,0,0,0,0,0,0,0
99998,00184094H,SOCIETE MATURINZI,2023,12,1372410,7624500,0,0,0,0,1372410,0
99999,00198615G,SERVICES AGRO-PASTORAUX DE L'ESPERANCE,2023,12,0,0,0,0,0,0,0,0

In [4]:
dgd = loader._extract_dgd_complete_with_nomenclature(oracle_engine)
dgd

2025-10-17 12:19:49,681 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-10-17 12:21:25,166 - core.data_loader - INFO - DGD extraite de la base Oracle: 720187 lignes

DGD extraite de la base Oracle: 720187 lignes

2025-10-17 12:21:27,609 - core.data_loader - INFO - Nomenclature fusionnée sur Code_Chapitre
2025-10-17 12:21:27,612 - core.data_loader - INFO - DGD complète extraite: 720187 lignes en 97.93s

,CODE_BUREAU,LIB_BUREAU,NUM_LIQUIDATION,DATE_LIQUIDATION,NUM_ARTICLE,NOMENCLATURE8,NOMENCLATURE10,LIBELLE,PAYS_ORIGINE,PAYS_DESTINATION1,...,TEP,TPC,TVT,ANNEE,CODE_CHAPITRE,Code Titre,Libellé_Titre,Lib_titre,Code_Chapitre,Lib_Chapitre
0,BFC02,OUAGA AEROPORT,L14158,2022-12-28,1,90189000,9018900000,"INSTRU &APP PR LA MEDECINE,CHIRURGIE,L'ART DEN...",Chine,Chine,...,NaN,NaN,NaN,2022,90,XVIII,"Instruments et appareils d'optique, de photogr...","Instruments et appareils d'optique, de photogr...",90,"INSTRUMENTS ET APPAREILS D'OPTIQUE, DE PHOTOGR..."
1,BFC03,OUAGA CDP,L5125,2023-07-17,2,90321000,9032100000,THERMOSTATS,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,90,XVIII,"Instruments et appareils d'optique, de photogr...","Instruments et appareils d'optique, de photogr...",90,"INSTRUMENTS ET APPAREILS D'OPTIQUE, DE PHOTOGR..."
2,BFC03,OUAGA CDP,L5125,2023-07-17,1,83021000,8302100000,CHARNIERES DE TOUS GENRES (Y COMPRIS LES PAUME...,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,83,XV,Métaux communs et ouvrages en ces métaux. Chap...,Métaux communs et ouvrages en ces métaux. Chap...,83,OUVRAGES DIVERS EN METAUX COMMUNS
3,BFC03,OUAGA CDP,L8494,2023-11-15,4,84189900,8418990000,PARTIES AUTRE QUE MEUBLES CONCUS POUR RECEVOIR...,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,84,XVI,Machines et appareils matériel électrique et l...,Machines et appareils matériel électrique et l...,84,"REACTEURS NUCLEAIRES, CHAUDIERES, MACHINES, AP..."
4,BFC03,OUAGA CDP,L8494,2023-11-15,2,84145900,8414590000,VENTILATEURS AUTRES QUE CEUX DU 8414.51,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,84,XVI,Machines et appareils matériel électrique et l...,Machines et appareils matériel électrique et l...,84,"REACTEURS NUCLEAIRES, CHAUDIERES, MACHINES, AP..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720182,BFW01,BOBO GARE,L14765,2025-09-17,1,87032320,8703232090,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Togo,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720183,BFC15,BVA (BUREAU VEHICULES AUTOMOBILES),L29415,2025-09-25,1,87032320,8703232010,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Etats-Unis,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720184,BFC15,BVA (BUREAU VEHICULES AUTOMOBILES),L30655,2025-10-07,1,87032320,8703232090,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Japon,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720185,BFC15,BVA (BUREAU VEHICULES AUTOMOBILES),L31461,2025-10-14,1,87032320,8703232090,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Etats-Unis,Etats-Unis,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720186,BFW01,BOBO GARE,L16297,2025-10-14,1,87032320,8703232010,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Etats-Unis,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."

In [5]:
dgd["ANNEE"].value_counts()

ANNEE
2024    239875
2025    221923
2023    211055
2022     47334
Name: count, dtype: int64

In [11]:
programm = loader._extract_programmation_controles(oracle_engine)
programm

2025-10-16 09:55:57,473 - core.data_loader - INFO - Extraction programmation et contrôles
2025-10-16 09:56:40,623 - core.data_loader - INFO - Programmation extraite: 652474 lignes en 43.15s

,NUM_IFU,DATE_IMMAT,NOM_MINEFID,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,DERNIERE_GESTION_SOUMIS_VERIF
0,00026275V,2010-04-21 00:00:00,MAMADOU TIEMTORE (COMPTOIR BURKINABE DE MARCHA...,None,NaT,None,None
1,00026276G,2010-04-21 00:00:00,ISSA TRAORE (I. T. F. SERVICES),None,NaT,None,None
2,00026277S,2010-04-21 00:00:00,ABDOUL MOUMOUNI PITROÏPA (TRICOM),2022-03-24 00:00:00,NaT,None,None
3,00026279M,2010-04-21 00:00:00,ALPHONSINE KANSOLE (KA MODE),None,NaT,None,None
4,00026281W,2010-04-21 00:00:00,DELWENDE SAMUEL BANDE (VISINE CONSEIL),None,NaT,None,None
...,...,...,...,...,...,...,...
652469,00284006H,2025-09-15 14:05:59,HADARA BELEM (BELHADA SERVICES FASHION),None,NaT,None,None
652470,00284007T,2025-09-15 14:07:14,RASMANE COMPAORE (RAHAB SOLUTION BF),None,NaT,None,None
652471,00283999K,2025-09-15 13:56:10,SALIF BAYO (ELEVAGE),None,NaT,None,None
652472,00284008U,2025-09-15 14:08:35,KADIDIATOU SANKARA (ETS SANKARA KADIDIATOU SER...,None,NaT,None,None
652473,00284009J,2025-09-15 14:09:55,ABBAS KOANDA (KOANDA ABBAS IMPORT- EXPORT),None,NaT,None,None

In [15]:
programm["NUM_IFU"].value_counts()

NUM_IFU
00033840Y    2
00071340X    2
00076174C    2
00005550Y    2
00000181B    2
            ..
00116807M    1
00116822J    1
00116844U    1
00116816Z    1
00116814B    1
Name: count, Length: 652185, dtype: int64

In [13]:
benefices = loader._extract_benefices_complete(oracle_engine)
benefices

2025-10-16 10:22:38,495 - core.data_loader - INFO - Extraction bénéfices complets
2025-10-16 10:30:01,013 - core.data_loader - INFO - Bénéfices extraits: 863075 lignes en 442.52s

          NUM_IFU  ANNEE_FISCAL CODE_ELT_LIQ  VALEUR_NUMERIQUE TYPE_BENEFICE
0       RF2126204          2022          118               NaN         IBICA
1       RF2126204          2022          120               NaN         IBICA
2       RF2126204          2022           69               NaN         IBICA
3       RF2126204          2022          117               NaN         IBICA
4       RF2126204          2022          115               NaN         IBICA
...           ...           ...          ...               ...           ...
863070  00276594F          2024          122               NaN          IBNC
863071  00276594F          2024          228               NaN          IBNC
863072  00276594F          2024          115               NaN          IBNC
863073  00276594F          2024          119               NaN          IBNC
863074  00276594F          2024           69               NaN          IBNC

[863075 rows x 5 columns]

In [4]:
insd = loader._extract_insd(oracle_engine)
insd

2025-10-17 10:27:30,367 - core.data_loader - INFO - Extraction INSD
2025-10-17 10:27:55,108 - core.data_loader - INFO - INSD extraite: 8818 lignes en 24.74s

,NUMERO_IFU,ID_INSD,ANNEE,FDP_ACQAPCREAT,BLLDS_ACQAPCREAT,BLLDS_VIREPOSTPOST,XA_MARGCOMMERC,XB_CA,XE_RESULT_EXPL,ETATTVA_ANNEEN,...,TOTAL_PVENDUEPAYS,AZ_TACTIFIMMOB_BRUT,BI_CLIENTS_NET,DN_PRCCT_NET,CP_TCPREA_NET,TPRC_ANNEEN,FR_ANNEEN,RK_CHARGDEPERSONNEL,RL_DOTAMORTPROVIDEP,XH_RESULTAT_HAO
0,00005679C,OUA2000A865-2023,2023,0,0,0,0,78988250,5249068,0.0,...,0.0,0.0,34944000.0,0.0,41411367.0,0.0,41411367.0,-1113600,0,0
128,00002168P,OUA2003 B 1036-2023,2023,0,0,0,-217496758,218836090,-190037212,25045963.0,...,0.0,2100000.0,0.0,0.0,53643287.0,0.0,53643287.0,-1531200,-600000,0
129,00009542B,OUA2007 A 043-2023,2023,0,0,0,-7590000,86629833,11985833,0.0,...,0.0,5321000.0,47596045.0,0.0,3902833.0,0.0,-1418167.0,-14820000,-1612000,0
130,00076515X,OUA2016B4143-2023,2023,0,0,0,0,139148530,10339625,0.0,...,0.0,67836302.0,24063000.0,0.0,-20715288.0,0.0,-37514124.0,-36437984,-7877052,-3776429
131,00099067P,OUA2017A9447-2023,2023,0,0,0,72750802,2492253700,9621020,73447.0,...,0.0,17101163.0,0.0,0.0,30959561.0,0.0,13858398.0,-15567200,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359102,00017238S,ZNR2013M002,2022,0,0,0,0,298468703,43534840,2556640.0,...,0.0,284480000.0,132506290.0,0.0,294863718.0,0.0,274918527.0,-7262650,-9632112,0
359203,00106447T,OUA2022M0246,2022,0,0,0,0,80157780,-25268703,0.0,...,0.0,202399999.0,15175897.0,0.0,49498905.0,0.0,-105542785.0,-17871901,-28361811,0
359204,00023338R,OUA2021M4689,2022,0,0,0,0,516227699,81390466,159702807.0,...,0.0,112987752.0,303589301.0,0.0,-155026787.0,26115693.0,-167238466.0,130845195,38386133,0
359205,00007211D,OUA2016M5335,2022,0,0,0,0,69199789,1904373,0.0,...,0.0,308754499.0,3227527.0,0.0,-142661269.0,0.0,-291898392.0,40441530,12566572,0
359206,00075456R,OUA2016B3421,2022,0,0,0,12439511,121529750,6514376,3656160.0,...,0.0,6968200.0,125185910.0,0.0,9593183.0,0.0,7680830.0,2530173,1565565,0

In [11]:
insd.duplicated().value_counts()

True     1527753
False       8818
Name: count, dtype: int64

In [10]:
insd[["NUMERO_IFU","ANNEE"]].duplicated().value_counts()

True     1529159
False       7412
Name: count, dtype: int64

In [12]:
insd.drop_duplicates()

,NUMERO_IFU,ID_INSD,ANNEE,FDP_ACQAPCREAT,BLLDS_ACQAPCREAT,BLLDS_VIREPOSTPOST,XA_MARGCOMMERC,XB_CA,XE_RESULT_EXPL,ETATTVA_ANNEEN,...,TOTAL_PVENDUEPAYS,AZ_TACTIFIMMOB_BRUT,BI_CLIENTS_NET,DN_PRCCT_NET,CP_TCPREA_NET,TPRC_ANNEEN,FR_ANNEEN,RK_CHARGDEPERSONNEL,RL_DOTAMORTPROVIDEP,XH_RESULTAT_HAO
0,00005679C,OUA2000A865-2023,2023,0,0,0,0,78988250,5249068,0.0,...,0.0,0.0,34944000.0,0.0,41411367.0,0.0,41411367.0,-1113600,0,0
128,00002168P,OUA2003 B 1036-2023,2023,0,0,0,-217496758,218836090,-190037212,25045963.0,...,0.0,2100000.0,0.0,0.0,53643287.0,0.0,53643287.0,-1531200,-600000,0
129,00009542B,OUA2007 A 043-2023,2023,0,0,0,-7590000,86629833,11985833,0.0,...,0.0,5321000.0,47596045.0,0.0,3902833.0,0.0,-1418167.0,-14820000,-1612000,0
130,00076515X,OUA2016B4143-2023,2023,0,0,0,0,139148530,10339625,0.0,...,0.0,67836302.0,24063000.0,0.0,-20715288.0,0.0,-37514124.0,-36437984,-7877052,-3776429
131,00099067P,OUA2017A9447-2023,2023,0,0,0,72750802,2492253700,9621020,73447.0,...,0.0,17101163.0,0.0,0.0,30959561.0,0.0,13858398.0,-15567200,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536466,00017238S,ZNR2013M002,2022,0,0,0,0,298468703,43534840,2556640.0,...,0.0,284480000.0,132506290.0,0.0,294863718.0,0.0,274918527.0,-7262650,-9632112,0
1536567,00106447T,OUA2022M0246,2022,0,0,0,0,80157780,-25268703,0.0,...,0.0,202399999.0,15175897.0,0.0,49498905.0,0.0,-105542785.0,-17871901,-28361811,0
1536568,00023338R,OUA2021M4689,2022,0,0,0,0,516227699,81390466,159702807.0,...,0.0,112987752.0,303589301.0,0.0,-155026787.0,26115693.0,-167238466.0,130845195,38386133,0
1536569,00007211D,OUA2016M5335,2022,0,0,0,0,69199789,1904373,0.0,...,0.0,308754499.0,3227527.0,0.0,-142661269.0,0.0,-291898392.0,40441530,12566572,0
1536570,00075456R,OUA2016B3421,2022,0,0,0,12439511,121529750,6514376,3656160.0,...,0.0,6968200.0,125185910.0,0.0,9593183.0,0.0,7680830.0,2530173,1565565,0

In [4]:
contribuable_data = loader.run_full_analysis()

2025-10-15 10:30:53,831 - core.data_loader - INFO - === DÉBUT DE L'ANALYSE COMPLÈTE ===
2025-10-15 10:30:53,834 - core.data_loader - INFO - === EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2025-10-15 10:30:54,008 - core.data_loader - INFO - Extraction contribuables
2025-10-15 10:31:26,708 - core.data_loader - INFO - Contribuables extraits: 215882/215882 après exclusions en 32.70s
2025-10-15 10:31:26,710 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-10-15 10:31:35,127 - core.data_loader - INFO - BD_TVA construite (R-compatible): 20659 lignes en 8.42s
2025-10-15 10:31:35,128 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-10-15 10:31:41,937 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 100000 lignes en 6.81s
2025-10-15 10:31:41,939 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-10-15 10:36:36,854 - core.data_loader - ERROR - Erreur lors de l'extraction DGD: 'DataLoader' object has no attribute 'nomenclature_sh'
2025-10-15 10:36:37,500 - core.data_loader - INFO - Extraction programmation et contrôles
2025-10-15 10:37:22,168 - core.data_loader - INFO - Programmation extraite: 652474 lignes en 44.67s
2025-10-15 10:37:22,169 - core.data_loader - INFO - Extraction bénéfices complets
2025-10-15 10:43:15,219 - core.data_loader - INFO - Bénéfices extraits: 863075 lignes en 353.05s
2025-10-15 10:43:15,244 - core.data_loader - INFO - === FUSION DES DONNÉES ===
2025-10-15 10:43:20,890 - core.data_loader - INFO - Données fusionnées: 1419453 lignes, 65 colonnes

In [12]:
contribuable_data

NameError: name 'contribuable_data' is not defined

In [12]:
contribuable_data["ANNEE_FISCAL_x"].value_counts()

ANNEE_FISCAL_x
2023.0    301263
2022.0    290830
2021.0    265623
Name: count, dtype: int64

In [11]:
contribuable_data["ANNEE_FISCAL_y"].value_counts()

ANNEE_FISCAL_y
2024.0    235707
2023.0    232415
2022.0    220476
2021.0    196924
2020.0    174435
2019.0    157990
2025.0      3388
Name: count, dtype: int64

In [7]:
contribuable_data["NUM_IFU"].value_counts()

NUM_IFU
00144015D    1440
00157569F    1188
00030439G    1182
00144016M     945
00116857X     864
             ...
00117776R       1
00007565C       1
00007564B       1
00007563F       1
00117760A       1
Name: count, Length: 215882, dtype: int64

In [7]:
merged_data = loader.run_extract_merge()

2025-12-17 11:26:19,551 - core.data_loader - INFO - === EXTRACTION & FUSION ===
2025-12-17 11:26:19,552 - core.data_loader - INFO -  1.=== EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2025-12-17 11:26:19,770 - core.data_loader - INFO - Extraction contribuables
2025-12-17 11:30:45,222 - core.data_loader - INFO - Exclusions appliquées: 4249 IFU exclus (6204 dans la liste d'exclusion)
2025-12-17 11:30:45,224 - core.data_loader - INFO - Contribuables extraits: 669966/674215 après exclusions en 265.45s
2025-12-17 11:30:45,224 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-12-17 11:31:06,907 - core.data_loader - INFO - BD_TVA construite (R-compatible): 59034 lignes en 21.68s
2025-12-17 11:31:06,908 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-12-17 11:31:48,421 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 62082 lignes en 41.51s
2025-12-17 11:31:48,421 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-12-17 11:32:22,547 - core.data_loader - INFO - DGD extraite de la base Oracle: 35143 lignes
2025-12-17 11:32:22,548 - core.data_loader - INFO - DGD complète extraite: 35143 lignes en 34.13s
2025-12-17 11:32:22,548 - core.data_loader - INFO - Extraction programmation et contrôles
2025-12-17 11:36:02,686 - core.data_loader - INFO - Programmation extraite: 674497 lignes en 220.14s
2025-12-17 11:36:02,686 - core.data_loader - INFO - Extraction bénéfices complets
2025-12-17 11:44:07,328 - core.data_loader - INFO - Bénéfices extraits: 830802 lignes en 484.64s
2025-12-17 11:44:07,328 - core.data_loader - INFO - Extraction INSD
2025-12-17 11:44:54,750 - core.data_loader - INFO - INSD extraite: 8818 lignes en 47.42s
2025-12-17 11:44:54,781 - core.data_loader - INFO - 2.=== FUSION DES DONNÉES ===
2025-12-17 11:44:55,006 - core.data_loader - INFO - Fusion BD_TVA + TVA_DEDUCTIONS réalisée: (86151, 50)
2025-12-17 11:44:55,282 - core.data_loader - INFO - Fusion TVA + DGD réalisée: (104683, 58)
2025-12-17 11:44:58,319 - core.data_loader - INFO - Fusion avec CONTRIBUABLES réalisée: (755066, 79)
2025-12-17 11:45:00,409 - core.data_loader - INFO - Fusion avec INSD réalisée: (757078, 99)
2025-12-17 11:45:02,708 - core.data_loader - INFO - Fusion avec PROGRAMMATION réalisée: (757952, 103)
2025-12-17 11:45:04,857 - core.data_loader - INFO - Fusion avec BENEFICES réalisée: (1091100, 107)
2025-12-17 11:45:04,857 - core.data_loader - INFO - Données fusionnées finales: 1091100 lignes, 107 colonnes

In [9]:
from core.risk_compute import RiskComputer

In [10]:
computer = RiskComputer()