In [1]:
from core.data_loader import DataLoader
from core.risk_compute import RiskComputer

In [2]:
import os
from db.ods import connectionOds
# Configuration des variables d'environnement
POSTGRES_DB_HOST = os.getenv("ODS_PG_HOST", "10.3.1.129")
POSTGRES_DB_PORT = os.getenv("ODS_PG_PORT", "5432")
POSTGRES_DB_USER = os.getenv("ODS_PG_USER", "postgres")
POSTGRES_DB_PASSWORD = os.getenv("ODS_PG_PASSWORD", "cpf2022")
POSTGRES_DB_NAME = os.getenv("ODS_PG_DB", "postgres")


# Initialisation des connexions aux bases de données
oracle_engine = connectionOds()

print(f"Postgres DB Host: {POSTGRES_DB_HOST} Port: {POSTGRES_DB_PORT} User: {POSTGRES_DB_USER} DB: {POSTGRES_DB_NAME}")

Connection to oracle SIDDGI database successful
Postgres DB Host: 10.3.1.129 Port: 5432 User: postgres DB: postgres

In [3]:
loader = DataLoader(oracle_engine)

2025-10-20 08:21:52,855 - core.data_loader - INFO - Chargement des données de référence...
2025-10-20 08:21:53,399 - core.data_loader - INFO - NON_EIGIBLE.xlsx chargé: 6204 IFU exclus
2025-10-20 08:21:53,421 - core.data_loader - INFO - Entreprises_LIEES.xlsx chargé: 100 lignes
2025-10-20 08:21:53,460 - core.data_loader - INFO - ../docs/META_DONNEES.xlsx chargé
2025-10-20 08:21:53,478 - core.data_loader - INFO - ../docs/FICHE_PISTES_INVESTIGATION.xlsx chargé
2025-10-20 08:21:53,784 - core.data_loader - INFO - ../docs/NomenclatureSH.xlsx chargé
2025-10-20 08:21:53,847 - core.data_loader - INFO - ../docs/DCF_ACTIVITES.xlsx chargé

In [4]:
merged_data = loader.run_full_analysis()

2025-10-20 08:21:56,526 - core.data_loader - INFO - === DÉBUT DE L'ANALYSE COMPLÈTE ===
2025-10-20 08:21:56,528 - core.data_loader - INFO - === EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2025-10-20 08:21:56,656 - core.data_loader - INFO - Extraction contribuables
2025-10-20 08:22:21,762 - core.data_loader - INFO - Exclusions appliquées: 3406 IFU exclus (6204 dans la liste d'exclusion)
2025-10-20 08:22:21,764 - core.data_loader - INFO - Contribuables extraits: 210820/214226 après exclusions en 25.11s
2025-10-20 08:22:21,766 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-10-20 08:22:25,557 - core.data_loader - INFO - BD_TVA construite (R-compatible): 20659 lignes en 3.79s
2025-10-20 08:22:25,559 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-10-20 08:22:30,936 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 99601 lignes en 5.38s
2025-10-20 08:22:30,937 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-10-20 08:23:57,791 - core.data_loader - INFO - DGD extraite de la base Oracle: 719482 lignes

DGD extraite de la base Oracle: 719482 lignes

2025-10-20 08:24:00,230 - core.data_loader - INFO - Nomenclature fusionnée sur Code_Chapitre
2025-10-20 08:24:00,232 - core.data_loader - INFO - DGD complète extraite: 719482 lignes en 89.29s
2025-10-20 08:24:00,234 - core.data_loader - INFO - Extraction programmation et contrôles
2025-10-20 08:24:32,607 - core.data_loader - INFO - Programmation extraite: 654822 lignes en 32.37s
2025-10-20 08:24:32,608 - core.data_loader - INFO - Extraction bénéfices complets
2025-10-20 08:31:33,398 - core.data_loader - INFO - Bénéfices extraits: 824571 lignes en 420.79s
2025-10-20 08:31:33,399 - core.data_loader - INFO - Extraction INSD
2025-10-20 08:31:55,405 - core.data_loader - INFO - INSD extraite: 8818 lignes en 22.00s
2025-10-20 08:31:55,410 - core.data_loader - INFO - === FUSION DES DONNÉES ===
2025-10-20 08:32:01,488 - core.data_loader - INFO - Données fusionnées: 1251050 lignes, 72 colonnes

In [6]:
computer = RiskComputer(loader)

In [8]:
computer.calculate_all_indicators(merged_data=merged_data[:100])

2025-10-20 10:59:54,865 - core.risk_compute - INFO - === CALCUL DE TOUS LES INDICATEURS ===
2025-10-20 10:59:55,126 - core.risk_compute - INFO - Calcul de tous les indicateurs terminé

      NUM_IFU ANNEE    RISQUE_IND_1   GAP_IND_1  SCORE_IND_1
0   00000003T   NaN  Non disponible         0.0            0
1   00000005J   NaN  Non disponible         0.0            0
2   00000007Y   NaN  Non disponible         0.0            0
3   00000018K   NaN  Non disponible         0.0            0
4   00000019F  2022           rouge  20117008.8           20
..        ...   ...             ...         ...          ...
95  00000019F  2023           rouge  20117008.8           20
96  00000019F  2023           rouge  20117008.8           20
97  00000019F  2023           rouge  20117008.8           20
98  00000019F  2023           rouge  20117008.8           20
99  00000019F  2023           rouge  20117008.8           20

[100 rows x 5 columns]

In [9]:
merged_data

,ID_CONTR,NUM_IFU,NOM_x,NOM_MINEFID_x,DATE_CREATION,DATE_IMMAT_x,ETAT,TEL,EMAIL,CODE_FJ,...,ANNEE_FISCAL_y,CODE_ELT_LIQ,VALEUR_NUMERIQUE,TYPE_BENEFICE,DATE_IMMAT_y,NOM_MINEFID_y,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,DERNIERE_GESTION_SOUMIS_VERIF
0,455301,00000003T,MAROU LENGLENGUE,MAROU LENGLENGUE,2006-01-12 00:00:00,2006-01-13 00:00:00,ACTIF,70-11-29-77,None,43,...,NaN,NaN,NaN,NaN,2006-01-13 00:00:00,MAROU LENGLENGUE,None,NaT,None,None
1,455656,00000005J,MAHAMADI ZOUNGRANA,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),2006-02-03 00:00:00,2006-02-03 00:00:00,ACTIF,50303511,None,43,...,NaN,NaN,NaN,NaN,2006-02-03 00:00:00,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),None,NaT,None,None
2,455304,00000007Y,CLEMENT BASSONO,CLEMENT BASSONO (GENIE MULTI-SERVICES),2006-01-12 00:00:00,2006-01-13 00:00:00,ACTIF,70-23-96-06,None,43,...,NaN,NaN,NaN,NaN,2006-01-13 00:00:00,CLEMENT BASSONO (GENIE MULTI-SERVICES),None,NaT,None,None
3,455310,00000018K,LAMOUSSA HAMED GANEMTORE,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,2006-01-16 00:00:00,2006-01-16 00:00:00,ACTIF,50-37-19-15,None,43,...,NaN,NaN,NaN,NaN,2006-01-16 00:00:00,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,None,NaT,None,None
4,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16 00:00:00,2006-01-16 00:00:00,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2019.0,76,NaN,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaT,2023-02-13 00:00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251045,1178813,00281794C,SOUMAILA SILGA,SOUMAILA SILGA (S.SILGA),2025-08-26 11:52:55,2025-08-26 13:52:55,ACTIF,+226-70-40-17-60,None,43,...,NaN,NaN,NaN,NaN,2025-08-26 13:52:55,SOUMAILA SILGA (S.SILGA),None,NaT,None,None
1251046,1178814,00281795Z,PHAROUCK OUMAROU ILBOUDO,PHAROUCK OUMAROU ILBOUDO (PHAROUCK ENERBAT),2025-08-26 11:53:47,2025-08-26 13:53:47,ACTIF,76-43-96-75,ILBOUDOPHAROUCKOUMAROU@GMAIL.C,43,...,NaN,NaN,NaN,NaN,2025-08-26 13:53:47,PHAROUCK OUMAROU ILBOUDO (PHAROUCK ENERBAT),None,NaT,None,None
1251047,1178767,00281797E,AZIZ SEDEGO,AZIZ SEDEGO (ENTREPRISE SEDEGO AZIZ),2025-08-26 11:56:42,2025-08-26 13:56:42,ACTIF,56-64-51-59,SEDEGOAZIZ94@GMAIL.COM,43,...,NaN,NaN,NaN,NaN,2025-08-26 13:56:42,AZIZ SEDEGO (ENTREPRISE SEDEGO AZIZ),None,NaT,None,None
1251048,1178820,00281798H,ABDOULAYE SEBGO,ABDOULAYE SEBGO (AKOS TRANSFERT),2025-08-26 11:58:27,2025-08-26 13:58:27,ACTIF,77-61-30-30,ABDOULAYESEBGO22@GMAIL.COM,43,...,NaN,NaN,NaN,NaN,2025-08-26 13:58:27,ABDOULAYE SEBGO (AKOS TRANSFERT),None,NaT,None,None
1251049,1178796,00281799T,RAGNANGNEWENDE BERTIN ILBOUDO,RAGNANGNEWENDE BERTIN ILBOUDO,2025-08-26 11:59:06,2025-08-26 13:59:06,ACTIF,00226-76-23-00-80,None,43,...,NaN,NaN,NaN,NaN,2025-08-26 13:59:06,RAGNANGNEWENDE BERTIN ILBOUDO,None,NaT,None,None

In [12]:
merged_data[["NUM_IFU", "ANNEE"]].duplicated().sum()

np.int64(1035562)

In [14]:
merged_data.groupby(["NUM_IFU", "ANNEE"]).size()

NUM_IFU    ANNEE
00000019F  2022     162
           2023     162
           2024     162
00000063X  2022     162
           2023     162
                   ...
00279676F  2025       1
00279870P  2025       1
00280248R  2025       1
00280287V  2025       1
00280794G  2025       1
Length: 10332, dtype: int64

In [ ]:
merged_data.groupby(["NUM_IFU", "ANNEE"]).size().reset_index(name='counts').query("counts > 1")

         NUM_IFU ANNEE  counts
0      00000019F  2022     162
1      00000019F  2023     162
2      00000019F  2024     162
3      00000063X  2022     162
4      00000063X  2023     162
...          ...   ...     ...
9984   00247700M  2025       9
9993   00248371X  2025       9
10021  00250218E  2024       9
10022  00250218E  2025       9
10045  00251561G  2025       9

[5255 rows x 3 columns]

In [6]:
computer.run_complete_analysis()

2025-10-17 16:12:45,028 - core.risk_compute - INFO - === DÉMARRAGE ANALYSE COMPLÈTE (MODULAIRE) ===
2025-10-17 16:12:45,031 - core.data_loader - INFO - === DÉBUT DE L'ANALYSE COMPLÈTE ===
2025-10-17 16:12:45,032 - core.data_loader - INFO - === EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2025-10-17 16:12:45,218 - core.data_loader - INFO - Extraction contribuables
2025-10-17 16:13:10,080 - core.data_loader - INFO - Exclusions appliquées: 3425 IFU exclus (6204 dans la liste d'exclusion)
2025-10-17 16:13:10,081 - core.data_loader - INFO - Contribuables extraits: 212506/215931 après exclusions en 24.86s
2025-10-17 16:13:10,083 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-10-17 16:13:15,473 - core.data_loader - INFO - BD_TVA construite (R-compatible): 20659 lignes en 5.39s
2025-10-17 16:13:15,475 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-10-17 16:13:22,265 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 99601 lignes en 6.79s
2025-10-17 16:13:22,267 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-10-17 16:15:02,624 - core.data_loader - INFO - DGD extraite de la base Oracle: 720187 lignes

DGD extraite de la base Oracle: 720187 lignes

2025-10-17 16:15:04,898 - core.data_loader - INFO - Nomenclature fusionnée sur Code_Chapitre
2025-10-17 16:15:04,900 - core.data_loader - INFO - DGD complète extraite: 720187 lignes en 102.63s
2025-10-17 16:15:04,901 - core.data_loader - INFO - Extraction programmation et contrôles
2025-10-17 16:15:45,507 - core.data_loader - INFO - Programmation extraite: 654378 lignes en 40.61s
2025-10-17 16:15:45,509 - core.data_loader - INFO - Extraction bénéfices complets
2025-10-17 16:21:29,091 - core.data_loader - INFO - Bénéfices extraits: 824355 lignes en 343.58s
2025-10-17 16:21:29,092 - core.data_loader - INFO - Extraction INSD
2025-10-17 16:21:49,287 - core.data_loader - INFO - INSD extraite: 8818 lignes en 20.19s
2025-10-17 16:21:49,293 - core.data_loader - INFO - === FUSION DES DONNÉES ===
2025-10-17 16:21:57,192 - core.data_loader - INFO - Données fusionnées: 1258644 lignes, 72 colonnes
2025-10-17 16:23:03,303 - core.risk_compute - INFO - === CALCUL DE TOUS LES INDICATEURS ===
2025-10-17 16:23:03,307 - core.risk_compute - ERROR - Erreur lors de l'analyse complète: 'NUM_IFU'
2025-10-17 16:23:03,322 - core.risk_compute - ERROR - Traceback (most recent call last):
  File "/media/Data/DGI/project/ana_risk/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7096, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'NUM_IFU'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/Data/DGI/project/ana_risk/src/core/risk_compute.py", line 114, in run_complete_analysis
    results_data = self.calculate_all_indicators(merged_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Data/DGI/project/ana_risk/src/core/risk_compute.py", line 65, in calculate_all_indicators
    result = TVAIndicators.calculate_indicator_1(merged_data, result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Data/DGI/project/ana_risk/src/indicateurs/tva_indicators.py", line 170, in calculate_indicator_1
    mask = (risk_df["NUM_IFU"] == numero_ifu) & (risk_df["ANNEE"] == annee)
            ~~~~~~~^^^^^^^^^^^
  File "/media/Data/DGI/project/ana_risk/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4107, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Data/DGI/project/ana_risk/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3819, in get_loc
    raise KeyError(key) from err
KeyError: 'NUM_IFU'

{'success': False,
 'error': "'NUM_IFU'",
 'nb_contribuables': 0,
 'nb_reports': 0,
 'message': "Erreur lors de l'analyse modulaire"}